### ISSUE TITLE
Add discord bot

### ISSUE THREAD

**Issue by cjbanna** [cjbanna/setlistbot#4]
### TODO

- [x] Add Discord infrastructure layer
- [x] Add new Discord specific reply builders
- [x] Add new Azure function to listen for Discord interactions
- [x] Add security check for incoming interaction requests
- [x] Add ping interaction handler
- [x] Add /setlist interaction handler
- [x] Register commands with Discord on app startup
